ERL-338: nemos-images-reference-lunar: add iotop dev package
Elektrobit/nemos-images pull request #43
Opened 2023-08-16 11:57 UTC by ahresse

2023-08-16 12:10 UTC, IsaacJT commented
Thanks @ahresse! I think this can be added to the standard package list, rather than just having it in the development profile

2023-08-23 07:33 UTC, IsaacJT requested changes
Please rebase against the latest changes

2023-08-23 08:05 UTC, ahresse commented
> Please rebase against the latest changes

Done

2023-08-23 09:11 UTC, IsaacJT approved these changes

2023-08-28 09:07 UTC, m-kat approved these changes

2023-08-28 09:59 UTC, merged