ERL-467: nemos-images-reference-*: *: add checkbox-erlangen-classic snap
Elektrobit/nemos-images pull request #55
Opened 2023-10-25 13:24 UTC by IsaacJT

Add the custom Checkbox snap created for the project. This contains all of the project-specific test suites that we require.

2023-10-26 07:54 UTC, IsaacJT commented
Requires https://github.com/Elektrobit/nemos-images/pull/54

2023-11-21 14:35 UTC, IsaacJT commented
Ready for review @ahresse @m-kat

2023-11-22 13:12 UTC, ahresse approved these changes
Works for me on development profile for mantic reference image.

```
# snap list checkbox-erlangen-classic
Name                       Version  Rev  Tracking       Publisher            Notes
checkbox-erlangen-classic  0.1dev   2    latest/stable  ce-certification-qa  classic
```

Thank you Isaac for adding spread tests.

2023-11-23 14:19 UTC, IsaacJT commented
CI fixed

2023-11-27 13:26 UTC, zongminl requested changes
Some changes required, please see my inline comments

2023-11-27 13:26 UTC, zongminl commented on nemos-images-reference-lunar/qemu-amd64/config.sh
> +        for snap in snapd checkbox22 checkbox checkbox-erlangen-classic core22; do
Let's remove the `checkbox` snap in this list, we don't need both checkbox and checkbox-erlangen-classic in NemOS image

2023-11-27 13:26 UTC, zongminl commented on nemos-images-reference-lunar/qemu-amd64/config.sh
> +            if [ "${snap}" = "checkbox" ] || [ "${snap}" = "checkbox-erlangen-classic" ]; then
`if [ "${snap}" = "checkbox-erlangen-classic" ]; then` would be good enough

2023-11-27 13:26 UTC, zongminl commented on nemos-images-reference-lunar/qemu-arm64/config.sh
> +        for snap in snapd checkbox22 checkbox checkbox-erlangen-classic core22; do
Let's remove the `checkbox` snap in this list, we don't need both checkbox and checkbox-erlangen-classic in NemOS image

2023-11-27 13:26 UTC, zongminl commented on nemos-images-reference-lunar/qemu-arm64/config.sh
> +            if [ "${snap}" = "checkbox" ] || [ "${snap}" = "checkbox-erlangen-classic" ]; then
`if [ "${snap}" = "checkbox-erlangen-classic" ]; then` would be good enough

2023-11-27 13:26 UTC, zongminl commented on nemos-images-reference-lunar/s32g274ardb2/config.sh
> +        for snap in snapd checkbox22 checkbox checkbox-erlangen-classic core22; do
Let's remove the `checkbox` snap in this list, we don't need both checkbox and checkbox-erlangen-classic in NemOS image

2023-11-27 13:26 UTC, zongminl commented on nemos-images-reference-lunar/s32g274ardb2/config.sh
> +            if [ "${snap}" = "checkbox" ] || [ "${snap}" = "checkbox-erlangen-classic" ]; then
`if [ "${snap}" = "checkbox-erlangen-classic" ]; then` would be good enough

2023-11-27 13:26 UTC, zongminl commented on nemos-images-reference-mantic/qemu-amd64/config.sh
> +        for snap in snapd checkbox22 checkbox checkbox-erlangen-classic core22; do
Let's remove the `checkbox` snap in this list, we don't need both checkbox and checkbox-erlangen-classic in NemOS image

2023-11-27 13:26 UTC, zongminl commented on nemos-images-reference-mantic/qemu-amd64/config.sh
> +            if [ "${snap}" = "checkbox" ] || [ "${snap}" = "checkbox-erlangen-classic" ]; then
`if [ "${snap}" = "checkbox-erlangen-classic" ]; then` would be good enough

2023-11-27 13:26 UTC, zongminl commented on nemos-images-reference-mantic/qemu-arm64/config.sh
> +        for snap in snapd checkbox22 checkbox checkbox-erlangen-classic core22; do
Let's remove the `checkbox` snap in this list, we don't need both checkbox and checkbox-erlangen-classic in NemOS image

2023-11-27 13:26 UTC, zongminl commented on nemos-images-reference-mantic/qemu-arm64/config.sh
> +            if [ "${snap}" = "checkbox" ] || [ "${snap}" = "checkbox-erlangen-classic" ]; then
`if [ "${snap}" = "checkbox-erlangen-classic" ]; then` would be good enough

2023-11-27 13:26 UTC, zongminl commented on nemos-images-reference-mantic/s32g274ardb2/config.sh
> +        for snap in snapd checkbox22 checkbox checkbox-erlangen-classic core22; do
Let's remove the `checkbox` snap in this list, we don't need both checkbox and checkbox-erlangen-classic in NemOS image

2023-11-27 13:26 UTC, zongminl commented on nemos-images-reference-mantic/s32g274ardb2/config.sh
> +            if [ "${snap}" = "checkbox" ] || [ "${snap}" = "checkbox-erlangen-classic" ]; then
`if [ "${snap}" = "checkbox-erlangen-classic" ]; then` would be good enough

2023-11-28 10:47 UTC, ahresse commented on nemos-images-reference-lunar/qemu-amd64/config.sh
> +        for snap in snapd checkbox22 checkbox checkbox-erlangen-classic core22; do
Should we remove both `checkbox22` and `checkbox` or only `checkbox`?

2023-11-28 15:00 UTC, zongminl commented on nemos-images-reference-lunar/qemu-amd64/config.sh
> +        for snap in snapd checkbox22 checkbox checkbox-erlangen-classic core22; do
We should still keep `checkbox22`, it provides all the required checkbox-runtime

2023-11-28 16:52 UTC, ahresse commented on nemos-images-reference-lunar/qemu-amd64/config.sh
> +            if [ "${snap}" = "checkbox" ] || [ "${snap}" = "checkbox-erlangen-classic" ]; then
https://github.com/Elektrobit/nemos-images/pull/55/commits/93053e6b6054c4c9fdb49869bb15599519a8657a

2023-11-28 16:52 UTC, ahresse commented on nemos-images-reference-lunar/qemu-arm64/config.sh
> +        for snap in snapd checkbox22 checkbox checkbox-erlangen-classic core22; do
https://github.com/Elektrobit/nemos-images/pull/55/commits/93053e6b6054c4c9fdb49869bb15599519a8657a

2023-11-28 16:52 UTC, ahresse commented on nemos-images-reference-lunar/qemu-arm64/config.sh
> +            if [ "${snap}" = "checkbox" ] || [ "${snap}" = "checkbox-erlangen-classic" ]; then
https://github.com/Elektrobit/nemos-images/pull/55/commits/93053e6b6054c4c9fdb49869bb15599519a8657a

2023-11-28 16:54 UTC, ahresse commented on nemos-images-reference-lunar/s32g274ardb2/config.sh
> +        for snap in snapd checkbox22 checkbox checkbox-erlangen-classic core22; do
https://github.com/Elektrobit/nemos-images/pull/55/commits/93053e6b6054c4c9fdb49869bb15599519a8657a

2023-11-28 16:54 UTC, ahresse commented on nemos-images-reference-mantic/qemu-amd64/config.sh
> +        for snap in snapd checkbox22 checkbox checkbox-erlangen-classic core22; do
https://github.com/Elektrobit/nemos-images/pull/55/commits/93053e6b6054c4c9fdb49869bb15599519a8657a

2023-11-28 16:54 UTC, ahresse commented on nemos-images-reference-mantic/qemu-amd64/config.sh
> +            if [ "${snap}" = "checkbox" ] || [ "${snap}" = "checkbox-erlangen-classic" ]; then
https://github.com/Elektrobit/nemos-images/pull/55/commits/93053e6b6054c4c9fdb49869bb15599519a8657a

2023-11-28 16:54 UTC, ahresse commented on nemos-images-reference-mantic/qemu-arm64/config.sh
> +        for snap in snapd checkbox22 checkbox checkbox-erlangen-classic core22; do
https://github.com/Elektrobit/nemos-images/pull/55/commits/93053e6b6054c4c9fdb49869bb15599519a8657a

2023-11-28 16:54 UTC, ahresse commented on nemos-images-reference-mantic/qemu-arm64/config.sh
> +            if [ "${snap}" = "checkbox" ] || [ "${snap}" = "checkbox-erlangen-classic" ]; then
https://github.com/Elektrobit/nemos-images/pull/55/commits/93053e6b6054c4c9fdb49869bb15599519a8657a

2023-11-30 08:08 UTC, IsaacJT commented
LGTM, thanks for the additions

2023-11-30 09:21 UTC, zongminl approved these changes
+1, thank you

2023-12-14 17:44 UTC, merged