debian: add Debian package dependencies
Elektrobit/nemos-images pull request #9
Opened 2023-03-30 11:51 UTC by IsaacJT

Add the dependencies which are required for building the images to the Debian package.

2023-03-30 12:45 UTC, schaefi requested changes
Thanks this is an important change. However, I think using the kiwi systemdeps concept can be an easier solution to the problem

2023-03-30 12:45 UTC, schaefi commented on debian/changelog
> +  * Add Kiwi build dependencies to the installed packages:
kiwi has a concept to make adding host requirements a bit easier. See here:

https://osinside.github.io/kiwi/concept_and_workflow/systemdeps.html

Therefore I think instead of adding a list of packages it would be better to just add the corresponding systemdeps package as a requirement. Thoughts ?

2023-03-30 12:53 UTC, IsaacJT commented on debian/changelog
> +  * Add Kiwi build dependencies to the installed packages:
I didn't realise these existed - I'll check if they meet the requirements :)

2023-04-05 13:40 UTC, IsaacJT commented
Hi @schaefi  I've replaced the dependencies with the `kiwi-systemdeps` package - thanks!

2023-04-05 14:02 UTC, schaefi commented
> Hi @schaefi I've replaced the dependencies with the `kiwi-systemdeps` package - thanks!

perfect that's how I thought it should look like in the end :) Thanks much

2023-04-05 14:50 UTC, merged